/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "register.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "passkey.login-options": [],
    "passkey.login": [],
    "passkey.confirm-options": [],
    "passkey.confirm": [],
    "passkey.registration-options": [],
    "passkey.store": [],
    "passkey.destroy": [
        {
            "name": "passkey",
            "required": true,
            "binding": "id"
        }
    ],
    "sanctum.csrf-cookie": [],
    "unisharp.lfm.show": [],
    "unisharp.lfm.getErrors": [],
    "unisharp.lfm.upload": [],
    "unisharp.lfm.getItems": [],
    "unisharp.lfm.move": [],
    "unisharp.lfm.doMove": [],
    "unisharp.lfm.getAddfolder": [],
    "unisharp.lfm.getFolders": [],
    "unisharp.lfm.getCrop": [],
    "unisharp.lfm.getCropImage": [],
    "unisharp.lfm.getNewCropImage": [],
    "unisharp.lfm.getRename": [],
    "unisharp.lfm.getResize": [],
    "unisharp.lfm.performResize": [],
    "unisharp.lfm.performResizeNew": [],
    "unisharp.lfm.getDownload": [],
    "unisharp.lfm.getDelete": [],
    "unisharp.lfm.": [],
    "menus.index": [],
    "menus.create": [],
    "menus.store": [],
    "menus.show": [
        {
            "name": "menu",
            "required": true
        }
    ],
    "menus.edit": [
        {
            "name": "menu",
            "required": true
        }
    ],
    "menus.update": [
        {
            "name": "menu",
            "required": true
        }
    ],
    "menus.destroy": [
        {
            "name": "menu",
            "required": true
        }
    ],
    "roles.index": [],
    "roles.create": [],
    "roles.store": [],
    "roles.show": [
        {
            "name": "role",
            "required": true
        }
    ],
    "roles.edit": [
        {
            "name": "role",
            "required": true
        }
    ],
    "roles.update": [
        {
            "name": "role",
            "required": true
        }
    ],
    "roles.destroy": [
        {
            "name": "role",
            "required": true
        }
    ],
    "permissions.index": [],
    "permissions.create": [],
    "permissions.store": [],
    "permissions.show": [
        {
            "name": "permission",
            "required": true
        }
    ],
    "permissions.edit": [
        {
            "name": "permission",
            "required": true
        }
    ],
    "permissions.update": [
        {
            "name": "permission",
            "required": true
        }
    ],
    "permissions.destroy": [
        {
            "name": "permission",
            "required": true
        }
    ],
    "departments.index": [],
    "departments.create": [],
    "departments.store": [],
    "departments.show": [
        {
            "name": "department",
            "required": true
        }
    ],
    "departments.edit": [
        {
            "name": "department",
            "required": true
        }
    ],
    "departments.update": [
        {
            "name": "department",
            "required": true
        }
    ],
    "departments.destroy": [
        {
            "name": "department",
            "required": true
        }
    ],
    "users.index": [],
    "users.create": [],
    "users.store": [],
    "users.show": [
        {
            "name": "user",
            "required": true
        }
    ],
    "users.edit": [
        {
            "name": "user",
            "required": true
        }
    ],
    "users.update": [
        {
            "name": "user",
            "required": true
        }
    ],
    "users.destroy": [
        {
            "name": "user",
            "required": true
        }
    ],
    "checkSMTP": [],
    "home": [],
    "dashboard": [],
    "menu": [],
    "menu.trash": [],
    "role": [],
    "role.trash": [],
    "role.permission": [
        {
            "name": "id",
            "required": true
        }
    ],
    "user": [],
    "user.trash": [],
    "company": [],
    "company.trash": [],
    "branch": [],
    "branch.trash": [],
    "department": [],
    "department.trash": [],
    "setting": [],
    "email_template": [],
    "email_setting.test_send": [],
    "403": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "security.edit": [],
    "user-password.update": [],
    "appearance.edit": [],
    "well-known.passkeys": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
