export const API_ENDPOINTS = {
    menus: '/api/menus',
    menuImport: '/api/menus/import',
    roles: '/api/roles',
    roleImport: '/api/roles/import',
    roleCheckName: '/api/roles/check-name',
    companies: '/api/companies',
    companyImport: '/api/companies/import',
    companyCheckCode: '/api/companies/check-code',
    companyCheckAdminIdentity: '/api/companies/check-admin-identity',
    companyGenerateCode: '/api/companies/generate-code',
    fetchCompanies: '/api/fetchcompanies',
    fetchBranches: '/api/fetchbranches',
    branches: '/api/branches',
    branchImport: '/api/branches/import',
    branchGenerateCode: '/api/branches/generate-code',
    users: '/api/users',
    userImport: '/api/users/import',
    userCheckIdentity: '/api/users/check-identity',
    departments: '/api/departments',
    departmentImport: '/api/departments/import',
    notifications: '/api/notifications',
} as const;
