export const API_ENDPOINTS = {
    menus: '/api/menus',
    menuImport: '/api/menus/import',
    roles: '/api/roles',
    roleImport: '/api/roles/import',
    roleCheckName: '/api/roles/check-name',
    companies: '/api/companies',
    companyImport: '/api/companies/import',
    companyCheckCode: '/api/companies/check-code',
    companyCheckAdminIdentity: '/api/companies/check-admin-identity',
    companyGenerateCode: '/api/companies/generate-code',
    companySendCredentials: (id: number | string) => `/api/companies/${id}/send-credentials`,
    companySettings: '/api/company-settings',
    softwareSettings: '/api/software-settings',
    softwareSettingsTestSmtp: '/api/software-settings/test-smtp',
    softwareSettingsTestSend: '/api/software-settings/test-send',
    fetchCurrencies: '/api/fetchcurrencies',
    currencies: '/api/currencies',
    currencyCheckCode: '/api/currencies/check-code',
    currencyFetchFromApi: '/api/currencies/fetch-from-api',
    countries: '/api/countries',
    countryCheckName: '/api/countries/check-name',
    countryCheckIso2: '/api/countries/check-iso2',
    countryFetchFromApi: '/api/countries/fetch-from-api',
    states: '/api/states',
    stateCheckName: '/api/states/check-name',
    stateFetchFromApi: '/api/states/fetch-from-api',
    cities: '/api/cities',
    cityCheckName: '/api/cities/check-name',
    cityFetchFromApi: '/api/cities/fetch-from-api',
    fetchTimezones: '/api/fetchtimezones',
    timezones: '/api/timezones',
    timezoneCheckName: '/api/timezones/check-name',
    timezoneFetchFromApi: '/api/timezones/fetch-from-api',
    fetchParentAccounts: '/api/fetchparentaccounts',
    fetchChildAccounts: '/api/fetchchildaccounts',
    fetchControlAccounts: '/api/fetchcontrolaccounts',
    chartOfAccounts: '/api/chart-of-accounts',
    chartOfAccountGenerateCode: '/api/chart-of-accounts/generate-code',
    chartOfAccountResolveFromParent: '/api/chart-of-accounts/resolve-from-parent',
    chartOfAccountCheckCode: '/api/chart-of-accounts/check-code',
    fetchParentSaleAccounts: '/api/fetchparentsaleaccounts',
    fetchParentPurchaseAccounts: '/api/fetchparentpurchaseaccounts',
    fetchCustomerGroups: '/api/fetchcustomergroups',
    fetchCustomers: '/api/fetchcustomers',
    contactDuplicates: '/api/contacts/duplicates',
    contactDuplicatesMerge: '/api/contacts/duplicates/merge',
    taxes: '/api/taxes',
    fetchTaxes: '/api/fetchtaxes',
    taxPreview: '/api/taxes/preview',
    financialYears: '/api/financialyears',
    fetchObAccounts: '/api/fetchobaccounts',
    accountBalances: '/api/account-balances',
    accountBalancesFetchBalance: '/api/account-balances/fetch-balance',
    fetchFinancialYears: '/api/fetchfinancialyears',
    fetchCompanies: '/api/fetchcompanies',
    fetchBranches: '/api/fetchbranches',
    branches: '/api/branches',
    branchImport: '/api/branches/import',
    branchGenerateCode: '/api/branches/generate-code',
    users: '/api/users',
    userImport: '/api/users/import',
    userCheckIdentity: '/api/users/check-identity',
    userSendCredentials: (id: number | string) => `/api/users/${id}/send-credentials`,
    departments: '/api/departments',
    departmentImport: '/api/departments/import',
    customerGroups: '/api/customer-groups',
    units: '/api/units',
    unitImport: '/api/units/import',
    unitCheckName: '/api/units/check-name',
    fetchUnits: '/api/fetchunits',
    warranties: '/api/warranties',
    warrantyImport: '/api/warranties/import',
    warrantyCheckName: '/api/warranties/check-name',
    fetchWarranties: '/api/fetchwarranties',
    brands: '/api/brands',
    brandImport: '/api/brands/import',
    brandCheckName: '/api/brands/check-name',
    fetchBrands: '/api/fetchbrands',
    categories: '/api/categories',
    categoryImport: '/api/categories/import',
    categoryCheckName: '/api/categories/check-name',
    fetchCategories: '/api/fetchcategories',
    fetchSubcategories: '/api/fetchsubcategories',
    itemTypes: '/api/item-types',
    itemTypeImport: '/api/item-types/import',
    itemTypeCheckName: '/api/item-types/check-name',
    fetchItemTypes: '/api/fetchitemtypes',
    variations: '/api/variations',
    variationImport: '/api/variations/import',
    fetchVariations: '/api/fetchvariations',
    products: '/api/products',
    productImport: '/api/products/import',
    productCheckName: '/api/products/check-name',
    productGenerateVariants: '/api/products/generate-variants',
    fetchProducts: '/api/fetchproducts',
    purchases: '/api/purchases',
    purchasePayments: '/api/purchase-payments',
    purchasePaymentEligiblePurchases: '/api/purchase-payments/eligible-purchases',
    purchasePaymentPurchase: (id: number | string) => `/api/purchase-payments/purchase/${id}`,
    purchasePaymentAccounts: '/api/purchase-payments/accounts',
    purchaseSearchProducts: '/api/purchases/search-products',
    purchaseApprovals: '/api/purchase-approvals',
    purchaseRequisitions: '/api/purchase-requisitions',
    purchaseRequisitionEligible: '/api/purchase-requisitions/eligible',
    purchaseRequisitionLines: (id: number | string) => `/api/purchase-requisitions/${id}/lines`,
    purchaseRequisitionApprovals: '/api/purchase-requisition-approvals',
    stockTransfers: '/api/stocktransfers',
    stockTransferSearchProducts: '/api/stocktransfers/search-products',
    stockAdjustments: '/api/stockadjustments',
    stockAdjustmentSearchProducts: '/api/stockadjustments/search-products',
    warehouses: '/api/warehouses',
    fetchWarehouses: '/api/fetchwarehouses',
    consumers: '/api/consumers',
    fetchConsumers: '/api/fetchconsumers',
    fetchAllAccounts: '/api/fetchallaccounts',
    bankIssuers: '/api/bank-issuers',
    fetchBankIssuers: '/api/fetchbankissuers',
    discounts: '/api/discounts',
    fetchDiscounts: '/api/fetchdiscounts',
    giftCards: '/api/gift-cards',
    giftCardOrphanRefunds: '/api/gift-cards/orphan-refunds',
    fetchGiftCards: '/api/fetchgiftcards',
    documentSettings: (group: string) => `/api/document-settings/${group}`,
    discountApply: '/api/discounts/apply',
    giftCardLookup: '/api/gift-cards/lookup',
    cashCollections: '/api/cash-collections',
    cashCollectionOpenInvoices: '/api/cash-collections/open-invoices',
    backups: '/api/backups',
    apiKeys: '/api/api-keys',
    currencyRates: '/api/currency-rates',
    portal: '/api/portal',
    portalChangePassword: '/api/portal/change-password',
    portalUsers: '/api/portal-users',
    portalSubscriptions: '/api/portal/subscriptions',
    portalSubscriptionPlans: '/api/portal/subscription-plans',
    portalSubscriptionChangePlan: (id: number | string) => `/api/portal/subscriptions/${id}/change-plan`,
    portalSubscriptionPause: (id: number | string) => `/api/portal/subscriptions/${id}/pause`,
    portalSubscriptionResume: (id: number | string) => `/api/portal/subscriptions/${id}/resume`,
    portalSubscriptionCancel: (id: number | string) => `/api/portal/subscriptions/${id}/cancel`,
    stockTakes: '/api/stock-takes',
    loyalty: '/api/loyalty',
    loyaltySettings: '/api/loyalty/settings',
    transporters: '/api/transporters',
    fetchTransporters: '/api/fetchtransporters',
    commissionAgents: '/api/commission-agents',
    fetchCommissionAgents: '/api/fetchcommissionagents',
    leads: '/api/leads',
    leadImport: '/api/leads/import',
    fetchLeads: '/api/fetchleads',
    leadSources: '/api/lead-sources',
    fetchLeadSources: '/api/fetchleadsources',
    fetchUsers: '/api/fetchusers',
    pipelineStages: '/api/pipeline-stages',
    fetchPipelineStages: '/api/fetchpipelinestages',
    opportunities: '/api/opportunities',
    opportunitiesBoard: '/api/opportunities/board',
    fetchOpportunities: '/api/fetchopportunities',
    activities: '/api/activities',
    activitiesTimeline: '/api/activities/timeline',
    priceLists: '/api/pricelists',
    priceListSearchProducts: '/api/pricelists/search-products',
    printLabelSearchProducts: '/api/printlabels/search-products',
    lowStock: '/api/lowstock',
    reports: '/api/reports',
    receivingNotes: '/api/receiving-notes',
    receivingNoteEligiblePurchases: '/api/receiving-notes/eligible-purchases',
    receivingNotePurchase: (id: number | string) => `/api/receiving-notes/purchase/${id}`,
    purchaseReturns: '/api/purchase-returns',
    purchaseReturnEligiblePurchases: '/api/purchase-returns/eligible-purchases',
    purchaseReturnPurchase: (id: number | string) => `/api/purchase-returns/purchase/${id}`,
    sells: '/api/sells',
    sellPayments: '/api/sell-payments',
    sellPaymentEligibleSells: '/api/sell-payments/eligible-sells',
    sellPaymentSell: (id: number | string) => `/api/sell-payments/sell/${id}`,
    sellPaymentAccounts: '/api/sell-payments/accounts',
    sellSearchProducts: '/api/sells/search-products',
    sellApprovals: '/api/sell-approvals',
    issueNotes: '/api/issue-notes',
    issueNoteEligibleSells: '/api/issue-notes/eligible-sells',
    issueNoteSell: (id: number | string) => `/api/issue-notes/sell/${id}`,
    sellReturns: '/api/sell-returns',
    sellReturnEligibleSells: '/api/sell-returns/eligible-sells',
    sellReturnSell: (id: number | string) => `/api/sell-returns/sell/${id}`,
    suppliers: '/api/suppliers',
    supplierGenerateCode: '/api/suppliers/generate-code',
    fetchSuppliers: '/api/fetchsuppliers',
    banks: '/api/banks',
    bankGenerateCode: '/api/banks/generate-code',
    fetchBanks: '/api/fetchbanks',
    linkBankCoa: (id: number | string) => `/api/banks/${id}/link-coa`,
    customers: '/api/customers',
    customerGenerateCode: '/api/customers/generate-code',
    fetchContactDetail: '/api/fetchcontactdetail',
    fetchLedger: '/api/fetchledger',
    contactLedgerWatches: '/api/contact-ledger-watches',
    journalEntries: '/api/journal-entries',
    journalEntryVoucherNo: '/api/journal-entries/voucher-no',
    journalEntryApprovals: '/api/journal-entry-approvals',
    paymentApprovals: '/api/payment-approvals',
    expenseApprovals: '/api/expense-approvals',
    depositApprovals: '/api/deposit-approvals',
    fundTransferApprovals: '/api/fund-transfer-approvals',
    creditDebitNoteApprovals: '/api/credit-debit-note-approvals',
    payments: '/api/payments',
    paymentVoucherNo: '/api/payments/voucher-no',
    expenses: '/api/expenses',
    expenseVoucherNo: '/api/expenses/voucher-no',
    deposits: '/api/deposits',
    depositVoucherNo: '/api/deposits/voucher-no',
    fundTransfers: '/api/fundtransfers',
    fundTransferVoucherNo: '/api/fundtransfers/voucher-no',
    creditDebitNotes: '/api/credit-debit-notes',
    creditDebitNoteVoucherNo: '/api/credit-debit-notes/voucher-no',
    linkSupplierCoa: (id: number | string) => `/api/suppliers/${id}/link-coa`,
    linkCustomerCoa: (id: number | string) => `/api/customers/${id}/link-coa`,
    notifications: '/api/notifications',
    subscriptionPlans: '/api/subscriptionplans',
    fetchSubscriptionPlans: '/api/fetchsubscriptionplans',
    coupons: '/api/coupons',
    fetchCoupons: '/api/fetchcoupons',
    tenants: '/api/tenants',
    tenantStatus: (id: number | string) => `/api/tenants/${id}/status`,
    tenantPlan: (id: number | string) => `/api/tenants/${id}/plan`,
    subscriptionInvoices: '/api/subscriptioninvoices',
    subscriptionInvoiceGenerate: '/api/subscriptioninvoices/generate',
    subscriptionInvoiceMarkPaid: (id: number | string) => `/api/subscriptioninvoices/${id}/mark-paid`,
    subscriptionInvoiceCancel: (id: number | string) => `/api/subscriptioninvoices/${id}/cancel`,
    webhooks: '/api/webhooks',
    webhookDeliveries: (id: number | string) => `/api/webhooks/${id}/deliveries`,
    apiLogs: '/api/apilogs',
    customerSubscriptionPlans: '/api/customersubscriptionplans',
    fetchCustomerSubscriptionPlans: '/api/fetchcustomersubscriptionplans',
    customerSubscriptions: '/api/customersubscriptions',
    customerSubscriptionChangePlan: (id: number | string) => `/api/customersubscriptions/${id}/change-plan`,
    customerSubscriptionPause: (id: number | string) => `/api/customersubscriptions/${id}/pause`,
    customerSubscriptionResume: (id: number | string) => `/api/customersubscriptions/${id}/resume`,
    customerSubscriptionCancel: (id: number | string) => `/api/customersubscriptions/${id}/cancel`,
    customerSubscriptionUsage: (id: number | string) => `/api/customersubscriptions/${id}/usage`,
    customerSubscriptionInvoices: '/api/customersubscriptioninvoices',
    customerSubscriptionInvoiceGenerate: '/api/customersubscriptioninvoices/generate',
    customerSubscriptionInvoiceMarkPaid: (id: number | string) => `/api/customersubscriptioninvoices/${id}/mark-paid`,
    customerSubscriptionInvoiceCancel: (id: number | string) => `/api/customersubscriptioninvoices/${id}/cancel`,
    customerSubscriptionInvoiceRefund: (id: number | string) => `/api/customersubscriptioninvoices/${id}/refund`,
    customerSubscriptionAnalyticsSummary: '/api/customersubscriptionanalytics/summary',
    customerSubscriptionAnalyticsChurn: '/api/customersubscriptionanalytics/churn',
    customerSubscriptionAnalyticsLtv: '/api/customersubscriptionanalytics/ltv',
    customerSubscriptionAnalyticsRevenue: '/api/customersubscriptionanalytics/revenue',
    customerSubscriptionAnalyticsRenewalDue: '/api/customersubscriptionanalytics/renewal-due',
} as const;
