export const API_ENDPOINTS = {
    menus: '/api/menus',
    menuImport: '/api/menus/import',
    roles: '/api/roles',
    roleImport: '/api/roles/import',
    roleCheckName: '/api/roles/check-name',
    companies: '/api/companies',
    companyImport: '/api/companies/import',
    companyCheckCode: '/api/companies/check-code',
    companyCheckAdminIdentity: '/api/companies/check-admin-identity',
    companyGenerateCode: '/api/companies/generate-code',
    companySendCredentials: (id: number | string) => `/api/companies/${id}/send-credentials`,
    companySettings: '/api/company-settings',
    softwareSettings: '/api/software-settings',
    softwareSettingsTestSmtp: '/api/software-settings/test-smtp',
    softwareSettingsTestSend: '/api/software-settings/test-send',
    fetchCurrencies: '/api/fetchcurrencies',
    currencies: '/api/currencies',
    currencyCheckCode: '/api/currencies/check-code',
    currencyFetchFromApi: '/api/currencies/fetch-from-api',
    countries: '/api/countries',
    countryCheckName: '/api/countries/check-name',
    countryCheckIso2: '/api/countries/check-iso2',
    countryFetchFromApi: '/api/countries/fetch-from-api',
    states: '/api/states',
    stateCheckName: '/api/states/check-name',
    stateFetchFromApi: '/api/states/fetch-from-api',
    cities: '/api/cities',
    cityCheckName: '/api/cities/check-name',
    cityFetchFromApi: '/api/cities/fetch-from-api',
    fetchTimezones: '/api/fetchtimezones',
    timezones: '/api/timezones',
    timezoneCheckName: '/api/timezones/check-name',
    timezoneFetchFromApi: '/api/timezones/fetch-from-api',
    fetchParentAccounts: '/api/fetchparentaccounts',
    fetchControlAccounts: '/api/fetchcontrolaccounts',
    chartOfAccounts: '/api/chart-of-accounts',
    chartOfAccountGenerateCode: '/api/chart-of-accounts/generate-code',
    chartOfAccountResolveFromParent: '/api/chart-of-accounts/resolve-from-parent',
    chartOfAccountCheckCode: '/api/chart-of-accounts/check-code',
    fetchParentSaleAccounts: '/api/fetchparentsaleaccounts',
    fetchParentPurchaseAccounts: '/api/fetchparentpurchaseaccounts',
    fetchCustomerGroups: '/api/fetchcustomergroups',
    fetchCustomers: '/api/fetchcustomers',
    taxes: '/api/taxes',
    fetchTaxes: '/api/fetchtaxes',
    financialYears: '/api/financialyears',
    fetchObAccounts: '/api/fetchobaccounts',
    accountBalances: '/api/account-balances',
    accountBalancesFetchBalance: '/api/account-balances/fetch-balance',
    fetchFinancialYears: '/api/fetchfinancialyears',
    fetchCompanies: '/api/fetchcompanies',
    fetchBranches: '/api/fetchbranches',
    branches: '/api/branches',
    branchImport: '/api/branches/import',
    branchGenerateCode: '/api/branches/generate-code',
    users: '/api/users',
    userImport: '/api/users/import',
    userCheckIdentity: '/api/users/check-identity',
    userSendCredentials: (id: number | string) => `/api/users/${id}/send-credentials`,
    departments: '/api/departments',
    departmentImport: '/api/departments/import',
    customerGroups: '/api/customer-groups',
    units: '/api/units',
    unitImport: '/api/units/import',
    unitCheckName: '/api/units/check-name',
    fetchUnits: '/api/fetchunits',
    warranties: '/api/warranties',
    warrantyImport: '/api/warranties/import',
    warrantyCheckName: '/api/warranties/check-name',
    fetchWarranties: '/api/fetchwarranties',
    brands: '/api/brands',
    brandImport: '/api/brands/import',
    brandCheckName: '/api/brands/check-name',
    fetchBrands: '/api/fetchbrands',
    categories: '/api/categories',
    categoryImport: '/api/categories/import',
    categoryCheckName: '/api/categories/check-name',
    fetchCategories: '/api/fetchcategories',
    fetchSubcategories: '/api/fetchsubcategories',
    itemTypes: '/api/item-types',
    itemTypeImport: '/api/item-types/import',
    itemTypeCheckName: '/api/item-types/check-name',
    fetchItemTypes: '/api/fetchitemtypes',
    variations: '/api/variations',
    variationImport: '/api/variations/import',
    fetchVariations: '/api/fetchvariations',
    products: '/api/products',
    productImport: '/api/products/import',
    productCheckName: '/api/products/check-name',
    productGenerateVariants: '/api/products/generate-variants',
    fetchProducts: '/api/fetchproducts',
    purchases: '/api/purchases',
    purchasePayments: '/api/purchase-payments',
    purchasePaymentEligiblePurchases: '/api/purchase-payments/eligible-purchases',
    purchasePaymentPurchase: (id: number | string) => `/api/purchase-payments/purchase/${id}`,
    purchasePaymentAccounts: '/api/purchase-payments/accounts',
    purchaseSearchProducts: '/api/purchases/search-products',
    purchaseApprovals: '/api/purchase-approvals',
    receivingNotes: '/api/receiving-notes',
    receivingNoteEligiblePurchases: '/api/receiving-notes/eligible-purchases',
    receivingNotePurchase: (id: number | string) => `/api/receiving-notes/purchase/${id}`,
    purchaseReturns: '/api/purchase-returns',
    purchaseReturnEligiblePurchases: '/api/purchase-returns/eligible-purchases',
    purchaseReturnPurchase: (id: number | string) => `/api/purchase-returns/purchase/${id}`,
    sells: '/api/sells',
    sellPayments: '/api/sell-payments',
    sellPaymentEligibleSells: '/api/sell-payments/eligible-sells',
    sellPaymentSell: (id: number | string) => `/api/sell-payments/sell/${id}`,
    sellPaymentAccounts: '/api/sell-payments/accounts',
    sellSearchProducts: '/api/sells/search-products',
    sellApprovals: '/api/sell-approvals',
    issueNotes: '/api/issue-notes',
    issueNoteEligibleSells: '/api/issue-notes/eligible-sells',
    issueNoteSell: (id: number | string) => `/api/issue-notes/sell/${id}`,
    sellReturns: '/api/sell-returns',
    sellReturnEligibleSells: '/api/sell-returns/eligible-sells',
    sellReturnSell: (id: number | string) => `/api/sell-returns/sell/${id}`,
    suppliers: '/api/suppliers',
    supplierGenerateCode: '/api/suppliers/generate-code',
    fetchSuppliers: '/api/fetchsuppliers',
    banks: '/api/banks',
    bankGenerateCode: '/api/banks/generate-code',
    fetchBanks: '/api/fetchbanks',
    linkBankCoa: (id: number | string) => `/api/banks/${id}/link-coa`,
    customers: '/api/customers',
    customerGenerateCode: '/api/customers/generate-code',
    fetchContactDetail: '/api/fetchcontactdetail',
    fetchLedger: '/api/fetchledger',
    contactLedgerWatches: '/api/contact-ledger-watches',
    journalEntries: '/api/journal-entries',
    journalEntryVoucherNo: '/api/journal-entries/voucher-no',
    payments: '/api/payments',
    paymentVoucherNo: '/api/payments/voucher-no',
    linkSupplierCoa: (id: number | string) => `/api/suppliers/${id}/link-coa`,
    linkCustomerCoa: (id: number | string) => `/api/customers/${id}/link-coa`,
    notifications: '/api/notifications',
} as const;
