<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

/**
 * A tenant-registered webhook endpoint (Settings > Integrations > Webhooks). `secret` is stored
 * encrypted (Eloquent's built-in `encrypted` cast — no new package) rather than hashed: unlike an API
 * key, which the SERVER only ever verifies a client-supplied value against, a webhook secret is
 * generated BY this app and used BY this app, repeatedly, to HMAC-sign every outgoing delivery so the
 * receiver can verify authenticity — the app must be able to read it back, so hashing (one-way) isn't an
 * option here.
 */
class Webhook extends Model
{
    use SoftDeletes;

    /**
     * @var list<string>
     */
    public const EVENTS = ['invoice.created', 'subscription.renewed', 'subscription.cancelled'];

    protected $fillable = [
        'company_id',
        'url',
        'events',
        'secret',
        'is_active',
    ];

    protected function casts(): array
    {
        return [
            'events' => 'array',
            'secret' => 'encrypted',
            'is_active' => 'boolean',
            'last_triggered_at' => 'datetime',
        ];
    }

    /**
     * @return BelongsTo<Company, $this>
     */
    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    /**
     * @return HasMany<WebhookDelivery, $this>
     */
    public function deliveries(): HasMany
    {
        return $this->hasMany(WebhookDelivery::class);
    }

    protected function secretPreview(): Attribute
    {
        return Attribute::make(
            get: fn () => $this->secret === null ? null : Str::mask($this->secret, '*', 4),
        );
    }

    public function scopeVisibleToCurrentUser(Builder $query): Builder
    {
        $user = Auth::user();

        if ($user?->hasRole('superadmin')) {
            return $query;
        }

        if (! $user?->company_id) {
            return $query->whereRaw('0 = 1');
        }

        return $query->where('company_id', $user->company_id);
    }

    public function subscribesTo(string $event): bool
    {
        return $this->is_active && in_array($event, (array) $this->events, true);
    }

    public static function createWebhook(object $request): self
    {
        $webhook = new self;
        $webhook->company_id = self::scopedCompanyId($request);
        $webhook->url = trim((string) $request->url);
        $webhook->events = array_values(array_intersect((array) $request->events, self::EVENTS));
        $webhook->secret = Str::random(40);
        $webhook->is_active = $request->has('is_active') ? $request->boolean('is_active') : true;
        $webhook->save();

        return $webhook;
    }

    public static function updateWebhook(object $request, int|string $id): self
    {
        $webhook = self::query()->visibleToCurrentUser()->findOrFail($id);
        $webhook->url = trim((string) $request->url);
        $webhook->events = array_values(array_intersect((array) $request->events, self::EVENTS));
        $webhook->is_active = $request->has('is_active') ? $request->boolean('is_active') : $webhook->is_active;
        $webhook->save();

        return $webhook;
    }

    public static function deleteWebhook(int|string $id): void
    {
        self::query()->visibleToCurrentUser()->find($id)?->delete();
    }

    private static function scopedCompanyId(object $request): ?int
    {
        $user = Auth::user();

        if ($user?->hasRole('superadmin')) {
            return $request->filled('company_id') ? (int) $request->company_id : null;
        }

        return $user?->company_id ? (int) $user->company_id : null;
    }
}
